### ISSUE TITLE
masked_cross_entrophy_nar_objective missing when testing on WOD

### ISSUE THREAD

**Issue by hunterls97** [HorizonRobotics/GUMP#6]
Hi @Yihanhu , thank you for sharing this great work!

I was able to build and run your docker container, and I downloaded the checkpoint from https://storage.googleapis.com/93935945854-us-central1-blueprint-config/gptm_wod.ckpt. I ran the caching scripts and was able to train successfully on WOD, however, when I try and run `test_wod_model.sh` I get a ModuleNotFoundError for masked_cross_entrophy_nar_objective when trying to load the checkpoint. I will include the traceback below.

```
Traceback (most recent call last):
  File "/root/workspace/GUMP/nuplan_extent/planning/script/run_training.py", line 114, in <module>
    main()
  File "/usr/local/lib/python3.9/dist-packages/hydra/main.py", line 49, in decorated_main
    _run_hydra(
  File "/usr/local/lib/python3.9/dist-packages/hydra/_internal/utils.py", line 367, in _run_hydra
    run_and_report(
  File "/usr/local/lib/python3.9/dist-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/usr/local/lib/python3.9/dist-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/usr/local/lib/python3.9/dist-packages/hydra/_internal/utils.py", line 368, in <lambda>
    lambda: hydra.run(
  File "/usr/local/lib/python3.9/dist-packages/hydra/_internal/hydra.py", line 110, in run
    _ = ret.return_value
  File "/usr/local/lib/python3.9/dist-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/usr/local/lib/python3.9/dist-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "/root/workspace/GUMP/nuplan_extent/planning/script/run_training.py", line 100, in main
    my_ckpt = torch.load(my_ckpt_path, map_location='cpu')
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 1025, in load
    return _load(opened_zipfile,
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 1446, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 1439, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'nuplan_extent.planning.training.modeling.objectives.masked_cross_entrophy_nar_objective'
```

It seems that there may be a module in the checkpoint that is not included in this branch?

**Comment by Yihanhu** [comment]
please try this https://storage.googleapis.com/93935945854-us-central1-blueprint-config/gptm_wod_test.ckpt
